// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJ-K1rSKT7CMkDLSd7iYwfxtSZn3SzHs',
    appId: '1:31361694882:web:e3c9fe17c890394b552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    authDomain: 'zerohm-nippou-app.firebaseapp.com',
    storageBucket: 'zerohm-nippou-app.appspot.com',
    measurementId: 'G-ZN9F0ZPG19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpecb_Q8yYwbdu7fW9BqncG0oBMJ3YxnE',
    appId: '1:31361694882:android:b9ffcfe12450332b552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    storageBucket: 'zerohm-nippou-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmrZoQuyeWnsuqU5l9dwgntDRzeQswBw',
    appId: '1:31361694882:ios:e9feaa86c0b01676552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    storageBucket: 'zerohm-nippou-app.appspot.com',
    iosClientId: '31361694882-u8mda680vq22cpce9qpnu6138eepgpqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nippou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmrZoQuyeWnsuqU5l9dwgntDRzeQswBw',
    appId: '1:31361694882:ios:c33267cad161f212552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    storageBucket: 'zerohm-nippou-app.appspot.com',
    iosClientId: '31361694882-pboubton9d77t73u3imhvtka30293b2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nippou.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJ-K1rSKT7CMkDLSd7iYwfxtSZn3SzHs',
    appId: '1:31361694882:web:85f5c0065398f649552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    authDomain: 'zerohm-nippou-app.firebaseapp.com',
    storageBucket: 'zerohm-nippou-app.appspot.com',
    measurementId: 'G-Z99VMHEPKC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCVJ-K1rSKT7CMkDLSd7iYwfxtSZn3SzHs',
    appId: '1:31361694882:web:797e63b1c372ce69552bfb',
    messagingSenderId: '31361694882',
    projectId: 'zerohm-nippou-app',
    authDomain: 'zerohm-nippou-app.firebaseapp.com',
    storageBucket: 'zerohm-nippou-app.appspot.com',
    measurementId: 'G-SQEE56SQ73',
  );
}
